<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home About', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-byxivr","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"40","bottom":"40"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":45.56,"Tablet":100,"Mobile":null},"elementId":"guten-e7s6oB","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"50","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-ovT8lH","content":"Welcome To Renovater Best Construction","textAlign":{"Mobile":"center","Desktop":"left"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"right":"70"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-BbcUsG","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"150"}} -->
<!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo perspiciatis unde omnis.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-bo36tw","spaceBetween":{"Desktop":"15","Mobile":""},"alignList":{"Mobile":"flex-start"},"verticalAlign":"flex-start","adjustVerticalAlign":{"Desktop":"12"},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconSize":{"Desktop":"15","Mobile":""},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textIndent":{"Desktop":"10","Mobile":""},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Mobile":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"10","left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-pqRGKR","icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","text":"Voluptatem accusantium doloremque laudantium","margin":{"Mobile":{"unit":"px","dimension":{"left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"left":""}}},"iconLineHeight":{"Desktop":"24"}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-lsL56L","icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","text":"Inventore veritatis et quasi architecto beatae vitae","iconLineHeight":{"Desktop":"24"}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-D3Frit","icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","text":"Perspiciatis unde omnis iste natus error sit voluptatem accusantiu","iconLineHeight":{"Desktop":"24"}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-V3ua88","icon":"fas fa-check","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDEwNS40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0yNTYgMjU2Yy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMGwtMTI4LTEyOGMtMTIuNS0xMi41LTEyLjUtMzIuOCAwLTQ1LjNzMzIuOC0xMi41IDQ1LjMgMEwxNjAgMzM4LjcgMzkzLjQgMTA1LjRjMTIuNS0xMi41IDMyLjgtMTIuNSA0NS4zIDB6Ii8+PC9zdmc+","text":"Inventore veritatis et quasi architecto beatae vitae","iconLineHeight":{"Desktop":"24"}} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/button {"elementId":"guten-abpOAt","content":"Read More","buttonSize":"lg","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"28"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"1300"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":27.42,"Tablet":50,"Mobile":null},"elementId":"guten-mLj5xy","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"hideMobile":true} -->
<!-- wp:gutenverse/image {"elementId":"guten-pilCbC","imgSrc":{"media":{"imageId":17,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":300,"width":201,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com_.webp","orientation":"portrait"},"large":{"height":1024,"width":686,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com_.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/iphone-mobile-person-model-spring-phone-513213-pxhere.com_.webp","height":2000,"width":1339,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"woman contractor call on the phone","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"ariaLabel":"woman contractor call on the phone","imageLoad":"lazy"} /-->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-WbhhES","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"20","safeNumber":"20","suffix":"+","title":"Years Experience","superTop":{"Desktop":""},"superSpace":{"Desktop":""},"numberColor":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"titleColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"numberTypography":{"size":{"Desktop":{"point":"28","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1"}},"font":{"label":"Roboto","value":"Roboto","type":"google"}},"titleTypography":{"lineHeight":{"Desktop":{"point":"","unit":"px"}},"font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"}},"numberBottomSpace":{"Desktop":""},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"background":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"border":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"20","color":{"type":"variable","id":"white"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-80","right":"40","bottom":"0","left":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"150"},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":27.01,"Tablet":50,"Mobile":null},"elementId":"guten-8bLC4o","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"bottom left"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"default"}},"horizontalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"},"hideMobile":true} -->
<!-- wp:gutenverse/icon {"elementId":"guten-0mQFpu","icon":"gtn gtn-play-button-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yNy40NjkgMTUuNzgxbC0yMi4wOTQtMTUuMjVxLTAuMTU2LTAuMTI1LTAuMzc1LTAuMTQxdC0wLjQwNiAwLjEwOXEtMC4xODggMC4wOTQtMC4yOTcgMC4yNjZ0LTAuMTA5IDAuMzkxdjMwLjQ2OXEwIDAuMjE5IDAuMTA5IDAuNDA2dDAuMjk3IDAuMjgxbDAuMTg4IDAuMDYzdDAuMTU2IDAuMDMxcTAuMTI1IDAgMC4yMzQtMC4wMzF0MC4yMDMtMC4xMjVsMjIuMDk0LTE1LjIxOXEwLjE1Ni0wLjEyNSAwLjI1LTAuMjgxdDAuMDk0LTAuMzQ0LTAuMDk0LTAuMzU5LTAuMjUtMC4yNjZ2MHoiPjwvcGF0aD4KPC9zdmc+Cg==","iconAlign":{"Desktop":"right"},"iconColorOne":{"type":"variable","id":"gv-color-accent"},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"15"},"iconColorTwo":{"type":"variable","id":"gv-color-text-primary"},"iconColorHoverOne":{"type":"variable","id":"gv-color-text-primary"},"iconColorHoverTwo":{"type":"variable","id":"white"},"iconShape":"square","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"solid","width":"20","color":{"type":"variable","id":"white"}},"right":{"type":"none"},"top":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-80"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"zIndex":{"Desktop":"21"},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/image {"elementId":"guten-lguQ9y","imgSrc":{"media":{"imageId":18,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":300,"width":200,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com_.webp","orientation":"portrait"},"large":{"height":1024,"width":682,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com_.webp","orientation":"portrait"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/ground-asphalt-construction-truck-vehicle-equipment-1132531-pxhere.com_.webp","height":2560,"width":1706,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"excavator parking","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"ariaLabel":"excavator parking","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
