<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Client Logo', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-OI1DiP","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"gv-color-secondary"},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-KbZEoK","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-K8vns0","imgSrc":{"media":{"imageId":83,"sizes":{"thumbnail":{"height":95,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-1.webp","orientation":"landscape"},"medium":{"height":61,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-1.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-1.webp","height":95,"width":471,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"ariaLabel":"client logo dummy 4","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-iAnJTM","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-nkb0oS","imgSrc":{"media":{"imageId":84,"sizes":{"thumbnail":{"height":102,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-3.webp","orientation":"landscape"},"medium":{"height":50,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-3.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-3.webp","height":102,"width":615,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"client logo dummy 3","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"ariaLabel":"client logo dummy 3","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-CwAQWF","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/image {"elementId":"guten-qe0PWV","imgSrc":{"media":{"imageId":85,"sizes":{"thumbnail":{"height":118,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-2.webp","orientation":"landscape"},"medium":{"height":68,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-2.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-2.webp","height":118,"width":519,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"30","bottom":"30","left":"30"}}},"ariaLabel":"client logo dummy 2","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"sectionVerticalAlign":"center","elementId":"guten-0Vpep2","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"240"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-5eIlwP","imgSrc":{"media":{"imageId":86,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-4.webp","orientation":"landscape"},"medium":{"height":72,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-4.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-partner-4.webp","height":161,"width":668,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"client logo dummy 2","captionOriginal":"","width":{"Desktop":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"opacity":"0.5","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"70","bottom":"","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"30","bottom":"30","left":"30"}}},"ariaLabel":"client logo dummy 2","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
