<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Content', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-V3zHzh","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"right":"15","left":"15"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":21,"Mobile":null},"elementId":"guten-3574LG","order":{"Mobile":1},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-2I2oj1","margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"12","right":"","left":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-qoKB4y","horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-mZyLyd","content":"Written By :","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/icon {"elementId":"guten-3iaLuc","icon":"fas fa-user-circle","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM5OSAzODQuMkMzNzYuOSAzNDUuOCAzMzUuNCAzMjAgMjg4IDMyMEgyMjRjLTQ3LjQgMC04OC45IDI1LjgtMTExIDY0LjJjMzUuMiAzOS4yIDg2LjIgNjMuOCAxNDMgNjMuOHMxMDcuOC0yNC43IDE0My02My44ek0wIDI1NmEyNTYgMjU2IDAgMSAxIDUxMiAwQTI1NiAyNTYgMCAxIDEgMCAyNTZ6bTI1NiAxNmE3MiA3MiAwIDEgMCAwLTE0NCA3MiA3MiAwIDEgMCAwIDE0NHoiLz48L3N2Zz4=","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-PvpO7I","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"14"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-secondary"},"authorBorder":{"radius":{"Desktop":[]}},"authorBorderResponsive":{"Desktop":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-2"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-PvpO7I"></div>
<!-- /wp:gutenverse/post-author -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-u9TVp3","margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"12"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-kbwSHT","horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-XIlfJ6","content":"Category :","type":3,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/icon {"elementId":"guten-hu9VJR","icon":"gtn gtn-folder2-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik03LjQ2OSAxMi41MzFxLTAuMDk0IDAtMC4xODggMC4wNjN0LTAuMDk0IDAuMTU2bC02LjEyNSAxNS4yNXYwLjUzMXEwIDAuMjgxIDAuMDMxIDAuNDA2dDAuMjgxIDAuMTI1aDIzLjg3NXEwLjQzOCAwIDAuODEzLTAuMjgxdDAuNDY5LTAuNjg4bDUuNDY5LTE1LjAzMXYtMC41MzFoLTI0LjUzMXpNNi43ODEgMTEuNDY5aDIyLjAzMXYtMy4zNDRxMC0wLjU5NC0wLjQzOC0xLjAzMXQtMS4wMzEtMC40MzhoLTEzLjE4OGwtMi42ODgtMy43MTloLTEwcS0wLjYyNSAwLTEuMDQ3IDAuNDIydC0wLjQyMiAxLjAxNnYyMi4zMTNsNS40NjktMTQuMjVxMC4xMjUtMC40MDYgMC40ODQtMC42ODh0MC44MjgtMC4yODF2MHoiPjwvcGF0aD4KPC9zdmc+Cg==","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-terms {"elementId":"guten-KQr2Dg","linkTo":"term","typography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"14"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-terms guten-KQr2Dg"></div>
<!-- /wp:gutenverse/post-terms -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-H4OamG","margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"12"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-xTspGM","horizontalAlign":{"Desktop":"default","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-LjnTd0","content":"Posted On :","type":3,"textAlign":{"Mobile":"center","Desktop":"left"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/icon {"elementId":"guten-uwfDu8","icon":"fas fa-calendar-alt","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTEyOCAwYzE3LjcgMCAzMiAxNC4zIDMyIDMyVjY0SDI4OFYzMmMwLTE3LjcgMTQuMy0zMiAzMi0zMnMzMiAxNC4zIDMyIDMyVjY0aDQ4YzI2LjUgMCA0OCAyMS41IDQ4IDQ4djQ4SDBWMTEyQzAgODUuNSAyMS41IDY0IDQ4IDY0SDk2VjMyYzAtMTcuNyAxNC4zLTMyIDMyLTMyek0wIDE5Mkg0NDhWNDY0YzAgMjYuNS0yMS41IDQ4LTQ4IDQ4SDQ4Yy0yNi41IDAtNDgtMjEuNS00OC00OFYxOTJ6bTY0IDgwdjMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWMjcyYzAtOC44LTcuMi0xNi0xNi0xNkg4MGMtOC44IDAtMTYgNy4yLTE2IDE2em0xMjggMHYzMmMwIDguOCA3LjIgMTYgMTYgMTZoMzJjOC44IDAgMTYtNy4yIDE2LTE2VjI3MmMwLTguOC03LjItMTYtMTYtMTZIMjA4Yy04LjggMC0xNiA3LjItMTYgMTZ6bTE0NC0xNmMtOC44IDAtMTYgNy4yLTE2IDE2djMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWMjcyYzAtOC44LTcuMi0xNi0xNi0xNkgzMzZ6TTY0IDQwMHYzMmMwIDguOCA3LjIgMTYgMTYgMTZoMzJjOC44IDAgMTYtNy4yIDE2LTE2VjQwMGMwLTguOC03LjItMTYtMTYtMTZIODBjLTguOCAwLTE2IDcuMi0xNiAxNnptMTQ0LTE2Yy04LjggMC0xNiA3LjItMTYgMTZ2MzJjMCA4LjggNy4yIDE2IDE2IDE2aDMyYzguOCAwIDE2LTcuMiAxNi0xNlY0MDBjMC04LjgtNy4yLTE2LTE2LTE2SDIwOHptMTEyIDE2djMyYzAgOC44IDcuMiAxNiAxNiAxNmgzMmM4LjggMCAxNi03LjIgMTYtMTZWNDAwYzAtOC44LTcuMi0xNi0xNi0xNkgzMzZjLTguOCAwLTE2IDcuMi0xNiAxNnoiLz48L3N2Zz4=","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-accent"},"iconShape":"circle","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-6cEdHW","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text-small","lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"14"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-6cEdHW"></div>
<!-- /wp:gutenverse/post-date -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-ksbbtN","content":"Share This :","type":3,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/social-share {"elementId":"guten-vwJKYn","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"textPading":{"Desktop":[]},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBackgroundColor":{"r":255,"g":255,"b":255,"a":0},"borderType":{"radius":{"Desktop":[]}},"iconColorHover":{"type":"variable","id":"gv-color-text-primary"},"borderTypeHover":{"radius":{"Desktop":[],"Mobile":[]}},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"alignment":{"Desktop":"flex-start","Mobile":"center"},"gap":{"Desktop":"20"}} -->
<div class="guten-element guten-social-share guten-vwJKYn horizontal"><!-- wp:gutenverse/social-share-facebook {"elementId":"guten-uZAGiP","showText":false,"iconSize":{"Desktop":{"unit":"px"}}} /-->

<!-- wp:gutenverse/social-share-twitter {"elementId":"guten-uqhzN4","showText":false} /-->

<!-- wp:gutenverse/social-share-whatsapp {"elementId":"guten-88Tzih","showText":false} /--></div>
<!-- /wp:gutenverse/social-share -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":79,"Mobile":null},"elementId":"guten-THwtWI","order":{"Mobile":2}} -->
<!-- wp:gutenverse/post-featured-image {"elementId":"guten-3Gq9IU","imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}}} -->
<div class="guten-element guten-post-featured-image guten-3Gq9IU"></div>
<!-- /wp:gutenverse/post-featured-image -->

<!-- wp:post-content {"tagName":"article"} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-Uw6hbV","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"gv-color-border-input"},"size":{"Desktop":"1"},"gap":{"Desktop":"60"}} /-->

<!-- wp:gutenverse/post-comment {"elementId":"guten-228S5E","typographyHeading":{"type":"variable","id":"gv-font-secondary-alt","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"typographyLink":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"typographyLabel":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"colorHeading":{"type":"variable","id":"gv-color-text-primary"},"colorLink":{"type":"variable","id":"gv-color-accent"},"marginHeading":{"Desktop":[]},"typographyText":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"colorText":{"type":"variable","id":"gv-color-text-secondary"},"marginText":{"Desktop":[]},"marginLink":{"Desktop":[]},"marginLabel":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"5"}}},"inputBorder":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"r":0,"g":0,"b":0,"a":0.25}}},"typographyButton":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"marginButton":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"28","left":"28","top":"22","bottom":"22"}}},"colorButton":{"type":"variable","id":"gv-color-text-primary"},"bgcolorButton":{"type":"variable","id":"gv-color-accent"},"borderButton":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputMargin":{"Desktop":[]},"inputPadding":{"Desktop":[]}} -->
<div class="guten-element guten-post-comment guten-228S5E"></div>
<!-- /wp:gutenverse/post-comment -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
