<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1290"},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":180,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/safety-health-worker-engineer-construction-industry-1575605-pxhere.com_.webp"}},"position":{"Desktop":"center right","Tablet":"center left"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover"},"videoPlayOnMobile":false,"fetchPriorityHigh":true},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.2","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","bottom":"160","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"240","bottom":"180","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"220","bottom":"220","right":"10","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-ejE6jy","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-8nzTzc","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":65,"Mobile":null},"elementId":"guten-jaZJOI","background":{"type":"default","color":{"type":"variable","id":"white"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"25","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"70","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"50","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"15","bottom":"60","left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"fast","delay":"0"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-VEFAkl","content":"Building The Future","type":1,"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"28"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"5","left":""}}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-0x6SGd","content":"Restoring The Past","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"56"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"28"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-lDMa5Z","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"right":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"40","left":""}}},"hideMobile":true} -->
<!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudanti totam rem aperiam&nbsp;</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":35},"elementId":"guten-6RAHjM"} /-->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-EfY2b3","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"-30","right":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"","right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"left":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
