<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Section', 'renovater' ),
	'categories' => array( 'renovater-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":28,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/tool-workshop-construction-repair-equipment-industrial-893399-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"r":3,"g":3,"b":3,"a":0.8}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"170","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"80"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-hPOdgn","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-a33bDf","content":"404","type":1,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-heading-404","lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"180"},"Tablet":{"unit":"px"},"Mobile":{"unit":"px","point":"100"}},"font":{"label":"Roboto","value":"Roboto","type":"google"},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-15","top":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-CyvafI","content":"Page Not Found","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"unit":"px"}}},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"top":"","bottom":"12"}},"Desktop":{"unit":"px","dimension":{"bottom":"24"}},"Tablet":[]},"padding":{"Mobile":[],"Desktop":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JTU9ow","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"33"}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>It looks like nothing was found at this location. Maybe try a search?</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-QDls3q","buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-dark-text-secondary"}},"inputPlaceholder":"search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"14","right":"14","top":"","bottom":""}}},"inputMargin":{"Desktop":[]},"inputHeight":{"Desktop":"55"},"inputWidth":{"Desktop":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"IBM Plex Sans","value":"IBM Plex Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":[]}},"alignContent":{"Desktop":"center"},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo="} -->
<!-- wp:gutenverse/button {"elementId":"guten-HeVWBW","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"24","left":"24","top":"","bottom":""}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-accent"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-secondary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"8","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"left":"0"}}},"color":{"type":"variable","id":"gv-color-text-primary"},"iconColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Roboto","value":"Roboto","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
